---
engine_version: 0.4.27
file_version: 2024-08-20 03:34:12.612156000 Z
resources: []
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  - conditions: []
    type: header
    name: Admin Jobs
    path: "./jobs"
    link_type: header
  updated_at: 2024-08-18 19:06:03.993216000 +00:00
queries: []
dashboards: []
forms:
- id: 1
  name: Import Contract
  http_method: POST
  api_path: "/api/import_contracts"
  description:
  preferences:
    fields:
    - display_name: File
      name: file
      field_type: file
      default_value: ''
      validators: []
    request_type: rest
  api_config_name: origin
  tags: []
  updated_at: 2024-08-20 03:34:12.612156000 +00:00
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2024-08-06 19:00:50.566859000 +00:00
