---
engine_version: 0.4.27
file_version: 2025-02-20 18:19:31.072071000 Z
resources:
- name: draft_pick
  preferences:
    actions:
    - name: swap_original_and_current
      display_name: Swap original and current
      action_type: method
      preferences:
        method_name: swap_original_and_current_team
        show_on_table: true
  updated_at: 2025-02-20 18:19:31.072071000 +00:00
- name: player
  preferences:
    actions:
    - name: roster
      display_name: Roster
      action_type: method
      preferences:
        method_name: roster!
    - name: non_roster
      display_name: Non Roster
      action_type: method
      preferences:
        method_name: non_roster!
  updated_at: 2025-01-25 00:44:34.454579000 +00:00
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  - conditions: []
    type: header
    name: Admin Jobs
    path: "./jobs"
    link_type: header
  updated_at: 2024-08-18 19:06:03.993216000 +00:00
queries: []
dashboards: []
forms:
- id: 1
  name: Import Contract
  http_method: POST
  api_path: "/api/import_contracts"
  description:
  preferences:
    fields:
    - display_name: File
      name: file
      field_type: file
      default_value: ''
      validators: []
    request_type: rest
  api_config_name: origin
  tags: []
  updated_at: 2024-08-20 03:34:12.612156000 +00:00
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2024-08-06 19:00:50.566859000 +00:00
