name: RSpec Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3 # Specify the Ruby version you're using
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ./NHL_SalaryCapSite
          
      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
        working-directory: ./NHL_SalaryCapSite

      - name: Run RSpec
        run: |
          bin/rails db:migrate RAILS_ENV=test
          bundle exec rspec
        working-directory: ./NHL_SalaryCapSite
